set(QUICKFIX_PUBLIC_HEADER_SOURCE_DIR "${PROJECT_SOURCE_DIR}/src/C++")
set(QUICKFIX_PUBLIC_HEADER_DEST_DIR "${PROJECT_SOURCE_DIR}/include/quickfix")

file(GLOB QUICKFIX_PUBLIC_HEADERS
  RELATIVE "${QUICKFIX_PUBLIC_HEADER_SOURCE_DIR}"
  "${QUICKFIX_PUBLIC_HEADER_SOURCE_DIR}/*.h")

list(REMOVE_ITEM QUICKFIX_PUBLIC_HEADERS "config.h")

if(NOT HAVE_SSL)
  list(FILTER QUICKFIX_PUBLIC_HEADERS EXCLUDE REGEX "^(SSL|ThreadedSSL|UtilitySSL).*\\.h$")
endif()

list(SORT QUICKFIX_PUBLIC_HEADERS)

set(QUICKFIX_FIX_HEADER_DIRS
  fix40
  fix41
  fix42
  fix43
  fix44
  fix50
  fix50sp1
  fix50sp2
  fixt11)

set(QUICKFIX_HEADER_COPY_COMMANDS
  COMMAND ${CMAKE_COMMAND} -E remove_directory "${QUICKFIX_PUBLIC_HEADER_DEST_DIR}/wx"
  COMMAND ${CMAKE_COMMAND} -E make_directory "${PROJECT_SOURCE_DIR}/include"
  COMMAND ${CMAKE_COMMAND} -E make_directory "${QUICKFIX_PUBLIC_HEADER_DEST_DIR}")

foreach(header IN LISTS QUICKFIX_PUBLIC_HEADERS)
  list(APPEND QUICKFIX_HEADER_COPY_COMMANDS
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
      "${QUICKFIX_PUBLIC_HEADER_SOURCE_DIR}/${header}"
      "${QUICKFIX_PUBLIC_HEADER_DEST_DIR}/${header}")
endforeach()

foreach(header_dir IN LISTS QUICKFIX_FIX_HEADER_DIRS)
  list(APPEND QUICKFIX_HEADER_COPY_COMMANDS
    COMMAND ${CMAKE_COMMAND} -E make_directory "${QUICKFIX_PUBLIC_HEADER_DEST_DIR}/${header_dir}"
    COMMAND ${CMAKE_COMMAND} -E copy_directory
      "${QUICKFIX_PUBLIC_HEADER_SOURCE_DIR}/${header_dir}"
      "${QUICKFIX_PUBLIC_HEADER_DEST_DIR}/${header_dir}")
endforeach()

add_custom_target(QUICKFIX_HEADERS_COPY ALL
  ${QUICKFIX_HEADER_COPY_COMMANDS})
