name: Build with CMake
on:
  push:
    branches: [master]
  pull_request:

jobs:
    build:
      runs-on: ${{ matrix.runner }}
      strategy:
          fail-fast: false
          matrix:
              runner: [windows-2022, ubuntu-latest, macos-latest]
              configuration: [Debug, Release]
              ssl: ['OFF', 'ON']
      steps:
      - name: Echo event_name ${{ github.event_name }}
        shell: bash
        run: echo "github.event_name $event_name"
        env:
          event_name: ${{ github.event_name }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install OpenSSL (macOS)
        if: matrix.ssl == 'ON' && matrix.runner == 'macos-latest'
        run: brew install openssl
      - name: Install OpenSSL (Linux)
        if: matrix.ssl == 'ON' && matrix.runner == 'ubuntu-latest'
        run: sudo apt-get install -y libssl-dev
      - name: Set OPENSSL_ROOT_DIR (macOS)
        if: matrix.ssl == 'ON' && matrix.runner == 'macos-latest'
        shell: bash
        run: echo "OPENSSL_ROOT_DIR=/opt/homebrew/opt/openssl" >> $GITHUB_ENV
      - name: Set OPENSSL_ROOT_DIR (Windows)
        if: matrix.ssl == 'ON' && matrix.runner == 'windows-2022'
        shell: bash
        run: echo "OPENSSL_ROOT_DIR=C:/Program Files/OpenSSL" >> $GITHUB_ENV
      - name: Generate
        shell: bash
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=$Configuration \
            -DHAVE_SSL=$SSL ${OPENSSL_ROOT_DIR:+-DOPENSSL_ROOT_DIR="$OPENSSL_ROOT_DIR"}
        env:
          Configuration: ${{ matrix.configuration }}
          SSL: ${{ matrix.ssl }}
          OPENSSL_ROOT_DIR: ${{ env.OPENSSL_ROOT_DIR }}
      - name: Build
        shell: bash
        run: |
          cmake --build build --config $Configuration
        env:
          Configuration: ${{ matrix.configuration }}
      - name: Run unit tests
        shell: bash
        run: |
          ctest --test-dir build --output-on-failure -C $Configuration -R '^ut$'
        env:
          Configuration: ${{ matrix.configuration }}
      - name: Run acceptance tests
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          ctest --test-dir build --output-on-failure -C $Configuration -R '^at$'
        env:
          Configuration: ${{ matrix.configuration }}
      - name: Run performance tests
        if: ${{ matrix.configuration == 'Release' }}
        shell: bash
        run: |
          ctest --test-dir build --output-on-failure -C Release -R '^pt$'
        env:
          Configuration: ${{ matrix.configuration }}
